### PR TITLE
never ever leave zombies lying around (using assassin.rb)

### PR DESCRIPTION
**Pull request by ahoward**

### CODE REVIEW

**Comment by ahoward** [comment]
any feedback / thoughts on this @thibaudgg ?

**Comment by thibaudgg** [comment]
Hey @ahoward, these zombies process defenitly need to be fixed but I'm wondering is doing it with an assassin script is the way to go. Is it really the standard way of killing zombies process? 

@ttilley @e2 @andreyvit what do you think?

Having the specs broken on Ruby 2.3.1 is aslo annoying, sadly I don't have much time to fix them at the moment.

**Comment by ahoward** [comment]
so so so hear you @thibaudgg but, here is the deal (i'd be over the moon if someone would correct me on being wrong)

- you have 'library' code burried deep in 'rails server' - no one knows it is even running ;-/
- the user, any gem, and app/ code, and process, can either invoke 'exit!' or send 'kill -9' to the front rails server process
- if that happens, all the ruby code you can write via 'at_exit', etc.  cannot reap the child process spawned by rb-fsevent.  it.  will.  leak.


the really key part here is that any gem, and signal, can make you gem look bad ;-/  go unix.


my basic approach, as an idealist library writer, is to make the following assertion true:

- i will create the resources i need

- nothing you do will make me not clean up after them



i will say, in this specific situation that, clearly, some combination of pre-forking (spring loader) and client behaviour (redis calling exit!, etc.) triggers some really, really bizarre behavior where 100s, not just 1, process is leaked but, in defense of my paranoid library writer mentality i will say "who cares"....  the invariate outlined above, which is only possible in unix by stepping sideways outside the process-tree-signal-hierarchy, is a methodology that "works when people fuck up" and "does no harm if everyone plays fair".  in truth, i think *every* ruby libraray that spawns a process should have a similar strategy.

finally, i welcome being proved wrong on this because it feels ugly.  but.  libary code often is ;-/

**Comment by spikex** [comment]
I agree that the solution is conceptually inelegant (the code itself is fine).  The correct solution is, to fix the library, of course. However, this is a real issue, and failing that option, something is needed.

 On my laptop (OS X 10.12) this morning:

```
% ps augxww | grep '[r]b-fsevent' | wc -l
      93
```

I suspect these were left behind by the *sqlite3* gem core dumping (fixed in 1.3.12), another path to `at_exit` being missed.

**Comment by ahoward** [comment]
the root cause lies somewhere here:

```bash
~ $ ruby -v
ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
~ $ rails -v
Rails 5.0.0.1
~ $ cd /tmp
tmp $ rm -rf leak; rails new leak >/dev/null 2>&1
tmp $ cd leak/
leak $ ps augxww | grep '[r]b-fsevent' | wc -l
       0
leak $ ./bin/rails runner :leak
Running via Spring preloader in process 15275
leak $ ps augxww | grep '[r]b-fsevent' | wc -l
      20
leak $ ./bin/rails runner :leak
Running via Spring preloader in process 15820
leak $ ps augxww | grep '[r]b-fsevent' | wc -l
      20
leak $ ./bin/spring stop
Spring stopped.
leak $ ps augxww | grep '[r]b-fsevent' | wc -l
       0
leak $ DISABLE_SPRING=42 ./bin/rails runner :leak
leak $ ps augxww | grep '[r]b-fsevent' | wc -l
       0
leak $ exit
```

**Comment by tmm1** [comment]
I believe if you added proper error handling on the `fprintf(stdout` invocations in fsevent_watch/main.c, you'd be able to catch the EPIPE that signals the parent process at the other end of the pipe has disappeared, and use that to exit(0).

**Comment by ahoward** [comment]
agree.  the only thing that is troubling me is understanding why on earth spring causes *20* of those to fire up ;-/  surely that affects more than just rb-fsevent....

**Comment by steakknife** [comment]
This is like mongrel all over again.... `fork: Resource temporarily unavailable` :(

**Comment by thibaudgg** [comment]
@ahoward what do you think of the #62 approach? Seems nicer to me.

**Comment by ahoward** [comment]
i do like this.   i'd merge it if i were you.  making the child never outlive the parent is needed.  having said that *no one* is understanding why spring makes __20__ of the damn things start and that needs looked at too.  if i were you i'd merge #62 and then, if that still wasn't enough ,this.  it is really, really, really bad.  at work we have entirely stopped using puma (/cc @evanphx) not because of anything wrong with it - but because puma + rails5 hits rb-fsevent and, in the course of a day, causes multiple laptops to freeze ;-/

**Comment by thibaudgg** [comment]
Version 0.9.8 released with @steakknife patch. Let me know if it fixes the issue for you guys. Thanks.

**Comment by ahoward** [comment]
+1

**Comment by e2** [comment]
Sorry, I'm crushed with work. Don't have OSX, either.

For OSX though, I'd suggest a client-server model. Like in Facebook's
Watchman listener. That way these processes would be managed by a
server that's auto-started and never dies (but would simply ignore
dead clients).

The burke/zeus project might have this solved already (though last
tiem I checked they use Go for both the server and the listeners).

Listen needs an overhaul to help with stuff like this (like
implementing the client-server model without much hassle), but again
... I'm crushed with work... sorry ;(

**Comment by steakknife** [comment]
Yup. Spawning individual servers is nuts.

**Comment by steakknife** [comment]
It should be pretty straightforward to get rid of all these fragile, support-intensive `Listen` adapters and just use watchman.  No more mongrel `fork: resource exhausted`, less duplicated/non-value-add effort.

https://github.com/facebook/watchman/tree/master/ruby/ruby-watchman

**Comment by danielrhodes** [comment]
@thibaudgg I am on 0.9.8 and still getting this on Mac

**Comment by ttilley** [comment]
please try again with 0.10.1

**Comment by spilth** [comment]
`bundle update rb-fsevent` brought me up to `rb-fsevent (0.10.2)` and seemed to get the number of `fsevent_watch` processes back down to a reasonable level.

**Pull request closed without merging**
