### PR TITLE
do not leak zombie processes even when killed with -9 or exit! is called

### PR DESCRIPTION
**Pull request by ahoward**
it is well known that rb-fsevent leaks processes if kill -9 or exit! is used.   given that it is baked into rails5 this is increasingly frustrating.

this fix makes damn sure that the spawn'd children are always cleaned up.

### CODE REVIEW

**Comment by ahoward** [comment]
ps.  i would like to add some tests but cannot get the suite to run under 2.3.1 ;-/

**Comment by thibaudgg** [comment]
@ahoward thanks, I'll have a look at the test suite. On which macOS version are you?

**Comment by ahoward** [comment]
10.11.6 (el cap).   ruby 2.3.1

fyi, i am factoring this approach out into a separate gem - any opinion on inlining vs. using a dependency?

**Comment by ahoward** [comment]
i've factored this out into a separate, testable, gem:

https://github.com/ahoward/assassin

i think we should nuke this PR and i'll submit another which simply adds the dep and a line or two of code.  agree @thibaudgg ?

**Comment by thibaudgg** [comment]
👍

**Pull request closed without merging**
